### ISSUE TITLE
Broken ghc after build (unlit and help missing)

### ISSUE THREAD

**Issue by kgardas** [snowleopard/shaking-up-ghc#181]
I've tested head master on Solaris and although the build is signaled as done the result is not working compiler:
```
karel@silence:/tmp/shake-test/bindisttest$ ../inplace/bin/ghc-stage2 --make HelloWorld.lhs 
ghc-stage2: could not execute: /tmp/shake-test/inplace/lib/bin/unlit
karel@silence:/tmp/shake-test/bindisttest$
$ ../inplace/bin/ghc-stage2 --help
/tmp/shake-test/inplace/lib/ghc-usage.txt: openFile: does not exist (No such file or directory)
karel@silence:/tmp/shake-test/bindisttest$ ../inplace/bin/ghc-stage2 --version
The Glorious Glasgow Haskell Compilation System, version 8.1.20160114
```
am I the only one seeing this or is this general issue?

**Comment by angerman** [comment]
I assume this is a general issue. unlit though I would have thought would exist. ghc-usage.txt is likely just not being copied.

**Comment by snowleopard** [comment]
We can easily add a rule to copy `ghc-usage.txt` and `ghci-usage.txt`.

Looks like `unlit` is missing because we never ask to build it! I'll fix this too.

**Comment by snowleopard** [comment]
OK, should be fixed now. Please reopen otherwise.

**Comment by thomie** [comment]
`unlit` is still missing for me, as are the following `utils`:
```
  hp2ps
  hpc
  runghc
  check-api-annotations
  ghc-iserv
```

This is with the same build as reported in #240, commit 6ef09f44f4c6128971ecaafda61b22cb0befa35c.

**Comment by snowleopard** [comment]
No idea why these are missing:
```
hp2ps
hpc
runghc
check-api-annotations
```
I think the root issue is #240.

As for `ghc-iserv`, I don't think we build it. We have the following in `GHC.hs`:
```haskell
iservBin        = topLevel "iserv-bin"      `setPath` "iserv" `setType` Program
```
@thomie Is this what you are looking for? I don't build this on Windows, so I have little knowledge what this is about. A couple of issues that may be relevant: #9, #102, #105.

**Comment by thomie** [comment]
> I think the root issue is #240.

Ah, right, these utils all depend on Cabal, so that makes sense. I'm doing another build now to verify.

> As for ghc-iserv, I don't think we build it. 

In my regular build, it is in `inplace/lib/bin/ghc-iserv`. It is used by `ghci -fexternal-interpreter` (https://ghc.haskell.org/trac/ghc/ticket/11100. I think the plan is to make that flag the default for ghci after some more testing. Facebook uses it already). It should work on Windows as well.

Build logic is in `iserv/ghc.mk`, for example:
```
iserv_PACKAGE = iserv-bin

iserv_stage2_PROGNAME = ghc-iserv
iserv_stage2_p_PROGNAME = ghc-iserv-prof
iserv_stage2_dyn_PROGNAME = ghc-iserv-dyn
```

**Comment by thomie** [comment]
Ok, after a succesful rebuild, only the following `utils` are missing:

* `inplace/bin/check-api-annotations`: I opened #242
* `inplace/lib/bin/ghc-iserv`: ticket #105

**Comment by snowleopard** [comment]
Great, thanks for clarifying. I'll handle #242 asap, but #105 may require a bit more work.
